

  development:
  adapter: postgresql
  database: prelaunchr
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: prelaunchr
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: prelaunchr
  pool: 5
  timeout: 5000
